import { PlanConfig } from '@/types';

export const PLANS: Record<string, PlanConfig> = {
  FREE: {
    id: 'FREE',
    name: 'Free',
    priceMonthly: 0,
    priceAnnual: 0,
    description: 'Perfect for trying out LocAI for your first local business website.',
    generationsLimit: 10,
    websitesLimit: 1,
    projectsLimit: 10,
    publishingLimit: 5,
    seoLevel: 'Basic',
    scheduling: false,
    teamMembers: 1,
    contentHistoryDays: 7,
    bulkGeneration: false,
    clientManagement: false,
    whiteLabel: false,
    features: [
      '10 AI Generations / mo',
      '1 WordPress Website',
      '10 Content Projects',
      '5 WordPress Publishes / mo',
      'Basic Local SEO Analysis',
      '7-day Content Version History',
      'Standard Support',
    ],
  },
  STARTER: {
    id: 'STARTER',
    name: 'Starter',
    priceMonthly: 9,
    priceAnnual: 90,
    description: 'Ideal for solo local service providers and independent freelancers.',
    generationsLimit: 100,
    websitesLimit: 2,
    projectsLimit: 100,
    publishingLimit: 50,
    seoLevel: 'Full',
    scheduling: true,
    teamMembers: 1,
    contentHistoryDays: 30,
    bulkGeneration: false,
    clientManagement: false,
    whiteLabel: false,
    features: [
      '100 AI Generations / mo',
      '2 WordPress Websites',
      '100 Content Projects',
      '50 WordPress Publishes / mo',
      'Full Local SEO Audit & Score',
      'Automated Post Scheduling',
      '30-day Content Version History',
      'Priority Email Support',
    ],
  },
  PRO: {
    id: 'PRO',
    name: 'Pro',
    priceMonthly: 29,
    priceAnnual: 290,
    description: 'For growing businesses and boutique marketing agencies managing multiple areas.',
    generationsLimit: 500,
    websitesLimit: 5,
    projectsLimit: 500,
    publishingLimit: 300,
    seoLevel: 'Advanced',
    scheduling: true,
    teamMembers: 3,
    contentHistoryDays: 90,
    bulkGeneration: true,
    clientManagement: false,
    whiteLabel: false,
    popular: true,
    features: [
      '500 AI Generations / mo',
      '5 WordPress Websites',
      '500 Content Projects',
      '300 WordPress Publishes / mo',
      'Advanced Local SEO Checklist',
      'Automated Post Scheduling',
      'Bulk Content Generator',
      'Advanced Internal Linking',
      '3 Team Member Seats',
      '90-day Version History & Restores',
    ],
  },
  AGENCY: {
    id: 'AGENCY',
    name: 'Agency',
    priceMonthly: 79,
    priceAnnual: 790,
    description: 'The complete local SEO powerhouse for high-volume agencies and consultants.',
    generationsLimit: 2000,
    websitesLimit: 20,
    projectsLimit: 'Unlimited',
    publishingLimit: 1500,
    seoLevel: 'Advanced',
    scheduling: true,
    teamMembers: 10,
    contentHistoryDays: 365,
    bulkGeneration: true,
    clientManagement: true,
    whiteLabel: true,
    features: [
      '2,000 AI Generations / mo',
      '20 WordPress Websites',
      'Unlimited Content Projects',
      '1,500 WordPress Publishes / mo',
      'Advanced Multi-location SEO',
      'Client Management Workspaces',
      'White-Label Client Reports',
      '10 Team Member Seats',
      '1-Year Version History',
      'Dedicated Account Manager & VIP Support',
    ],
  },
};

export const CONTENT_TYPE_LABELS: Record<string, { label: string; badge: string; description: string }> = {
  LOCAL_SERVICE_PAGE: {
    label: 'Local Service Page',
    badge: 'Service',
    description: 'Targeted service page for a specific town or service area (e.g., Emergency Plumbing Services in Mardan)',
  },
  LOCATION_PAGE: {
    label: 'Location Page',
    badge: 'Location',
    description: 'Dedicated landing page for a target city or neighborhood (e.g., Best Plumbing Services in Mardan)',
  },
  SERVICE_LOCATION_PAGE: {
    label: 'Service + Location Page',
    badge: 'Geo-Target',
    description: 'Hyper-specific keyword combination (e.g., Emergency Plumber in Peshawar)',
  },
  BLOG_ARTICLE: {
    label: 'Local Blog Article',
    badge: 'Article',
    description: 'In-depth informative post answering local resident questions (e.g., How to Choose a Reliable Plumber)',
  },
  FAQ: {
    label: 'Local FAQ Page',
    badge: 'FAQ',
    description: 'Schema-rich frequently asked questions for rich snippet visibility',
  },
  BUSINESS_DESCRIPTION: {
    label: 'Business Profile & Overview',
    badge: 'Profile',
    description: 'Authoritative description optimized for directory listings and about pages',
  },
  GBP_POST: {
    label: 'Google Business Profile Post',
    badge: 'GBP Post',
    description: 'Short, engaging promotional update with local CTA for Google Maps presence',
  },
  SEO_METADATA: {
    label: 'SEO Metadata Suite',
    badge: 'Metadata',
    description: 'Optimized meta titles, meta descriptions, slugs, and focus keyword clusters',
  },
};
